<?php
/**

 * @category   Rootinfo
 * @package    Rootinfo_Socialconnect
 * @copyright  Copyright (c) 2014-2015 (http://rootinfosol.com/)
 
 */
?>
<div class="clearer">
    <div class="rootinfo-socialconnect-facebook">
        <div class="rootinfo-socialconnect-facebook-inner">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <!--<div class="rootinfo-socialconnect-facebook-right"></div>-->
    </div>
</div>
