<?php
/**
* Rootinfo
*
* NOTICE OF LICENSE
*
* This source file is subject to the Open Software License (OSL 3.0)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://opensource.org/licenses/osl-3.0.php
* If you did not receive a copy of the license and are unable to
* obtain it through the world-wide-web, please send an email
* to license@magentocommerce.com so we can send you a copy immediately.
*
* DISCLAIMER
*
* However,* Rootinfo *guarantee functional accuracy of
* specific extension behavior. Additionally we take no responsibility
* for any possible issue(s) resulting from extension usage.
* We reserve the full right not to provide any kind of support for our free extensions.
* Thank you for your understanding.
* @category   Rootinfo
* @package    Rootinfo_Socialconnect
* @author     Shekhar <shekhar@rootinfosol.com>
* @copyright  Copyright (c) 2014-2015 (http://rootinfosol.com/)
* @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/

?>
<div class="rootinfo-socialconnect-login">
    <div class="account-login">
        
        
        <div class="<?php echo $this->_getColSet(); ?> rootinfo-socialconnect-login-lower">
            <?php if($this->_googleEnabled()): ?>
            <div class="<?php echo $this->_getButtCol(); ?> rootinfo-socialconnect-login-lower-google">
                <div class="buttons-set">
                    <?php //echo $this->getChildHtml('rootinfo_socialconnect_google_login_button'); ?>
                    <?php echo $this->getLayout()->createBlock('rootinfo_socialconnect/google_button')->setTemplate('rootinfo/socialconnect/google/button.phtml')->toHtml(); ?>
                </div>
            </div>
            <?php endif; ?>
            <?php if($this->_facebookEnabled()): ?>
            <div class="<?php echo $this->_getButtCol(); ?> rootinfo-socialconnect-login-lower-facebook">
                <div class="buttons-set">
                    <?php //echo $this->getChildHtml('rootinfo_socialconnect_facebook_login_button'); ?>
                    <?php echo $this->getLayout()->createBlock('rootinfo_socialconnect/facebook_button')->setTemplate('rootinfo/socialconnect/facebook/button.phtml')->toHtml(); ?>
                </div>
            </div>
            <?php endif; ?>
            <?php if($this->_twitterEnabled()): ?>
            <div class="<?php echo $this->_getButtCol(); ?> rootinfo-socialconnect-login-lower-twitter">
                <div class="buttons-set">
                    <?php //echo $this->getChildHtml('rootinfo_socialconnect_twitter_login_button'); ?>
                
                  <?php echo $this->getLayout()->createBlock('rootinfo_socialconnect/twitter_button')->setTemplate('rootinfo/socialconnect/twitter/button.phtml')->toHtml(); ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>
